//! Taint Tracking Module
//!
//! Tracks how sensitive data flows through the system.
//! Implements taint analysis to prevent unauthorized data exposure.

use super::SensitivityLevel;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use sha2::{Sha256, Digest};

/// Taint source - where sensitive data originates
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct TaintSource {
    /// Unique source ID
    pub id: String,

    /// Source type (as string)
    pub source_type: String,

    /// Sensitivity of data from this source
    pub sensitivity: String,

    /// When this source was registered
    pub registered_at: f64,

    /// Tags for this source
    pub tags: Vec<String>,
}

/// Type of taint source
#[derive(Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[napi(string_enum)]
pub enum TaintSourceType {
    /// User input
    UserInput,
    /// File system
    FileSystem,
    /// Network/API
    Network,
    /// Environment variables
    Environment,
    /// Secrets manager
    Secrets,
    /// Database
    Database,
    /// Generated by agent
    AgentGenerated,
    /// Tool output
    ToolOutput,
    /// Memory/context
    Memory,
    /// External system
    External,
}

/// A tainted data item
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct TaintedData {
    /// Unique taint ID
    pub id: String,

    /// Source of the taint
    pub source_id: String,

    /// Data hash (not the actual data)
    pub data_hash: String,

    /// Sensitivity level
    pub sensitivity: String,

    /// Where this data currently resides
    pub location: DataLocation,

    /// Propagation chain
    pub propagated_from: Vec<String>,

    /// When this was tainted
    pub tainted_at: f64,

    /// Whether this can be decontaminated
    pub can_sanitize: bool,

    /// Last access time
    pub last_accessed: f64,

    /// Access count
    pub access_count: f64,
}

/// Location of tainted data
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct DataLocation {
    /// Location type
    pub location_type: String,

    /// Specific identifier (file path, variable name, etc.)
    pub identifier: String,

    /// Context (function, module, etc.)
    pub context: Option<String>,
}

/// Taint propagation record
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct TaintPropagation {
    /// Propagation ID
    pub id: String,

    /// Source taint ID
    pub source_id: String,

    /// Target taint ID
    pub target_id: String,

    /// How the taint propagated (as string)
    pub propagation_type: String,

    /// Operation that caused propagation
    pub operation: String,

    /// When propagation occurred
    pub timestamp: f64,
}

/// How taint propagates
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[napi(string_enum)]
pub enum PropagationType {
    /// Direct assignment
    Assignment,
    /// Function parameter
    Parameter,
    /// Return value
    Return,
    /// String concatenation
    Concatenation,
    /// Array/collection inclusion
    CollectionInclusion,
    /// Object property
    Property,
    /// Transformation (encoding, encryption)
    Transformation,
    /// Aggregation (sum, combine)
    Aggregation,
}

/// Taint tracking engine
pub struct TaintTracker {
    /// Registered taint sources
    sources: HashMap<String, TaintSource>,

    /// Tainted data items
    tainted: HashMap<String, TaintedData>,

    /// Propagation history
    propagations: Vec<TaintPropagation>,

    /// Data hash to taint ID mapping
    hash_to_taint: HashMap<String, String>,

    /// Sinks that can receive tainted data
    allowed_sinks: HashMap<String, SinkPolicy>,

    /// Statistics
    stats: TaintStats,
}

/// Policy for a sink
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct SinkPolicy {
    max_sensitivity: SensitivityLevel,
    require_sanitization: bool,
    audit_all: bool,
}

/// Taint statistics
#[derive(Debug, Clone, Default)]
struct TaintStats {
    total_sources: f64,
    total_tainted: f64,
    total_propagations: f64,
    by_source_type: HashMap<String, f64>,
    by_sensitivity: HashMap<String, f64>,
}

impl Default for TaintTracker {
    fn default() -> Self {
        Self::new()
    }
}

impl TaintTracker {
    pub fn new() -> Self {
        let mut tracker = TaintTracker {
            sources: HashMap::new(),
            tainted: HashMap::new(),
            propagations: Vec::new(),
            hash_to_taint: HashMap::new(),
            allowed_sinks: HashMap::new(),
            stats: TaintStats::default(),
        };

        tracker.register_default_sinks();
        tracker
    }

    fn register_default_sinks(&mut self) {
        // Console output - only allow low sensitivity
        self.allowed_sinks.insert(
            "console".to_string(),
            SinkPolicy {
                max_sensitivity: SensitivityLevel::Internal,
                require_sanitization: true,
                audit_all: true,
            },
        );

        // File writes - allow up to confidential
        self.allowed_sinks.insert(
            "file".to_string(),
            SinkPolicy {
                max_sensitivity: SensitivityLevel::Confidential,
                require_sanitization: false,
                audit_all: false,
            },
        );

        // Network - very restrictive
        self.allowed_sinks.insert(
            "network".to_string(),
            SinkPolicy {
                max_sensitivity: SensitivityLevel::Public,
                require_sanitization: true,
                audit_all: true,
            },
        );

        // Logs - no sensitive data
        self.allowed_sinks.insert(
            "log".to_string(),
            SinkPolicy {
                max_sensitivity: SensitivityLevel::Internal,
                require_sanitization: true,
                audit_all: true,
            },
        );
    }

    /// Register a taint source
    pub fn register_source(
        &mut self,
        source_type: TaintSourceType,
        sensitivity: SensitivityLevel,
        tags: Vec<String>,
    ) -> String {
        let id = generate_taint_id();

        let source = TaintSource {
            id: id.clone(),
            source_type: format!("{:?}", source_type).to_lowercase(),
            sensitivity: sensitivity.name().to_lowercase(),
            registered_at: current_timestamp(),
            tags,
        };

        *self.stats.by_source_type
            .entry(format!("{:?}", source_type))
            .or_insert(0.0) += 1.0;
        self.stats.total_sources += 1.0;

        self.sources.insert(id.clone(), source);
        id
    }

    /// Taint data from a source
    pub fn taint_data(
        &mut self,
        source_id: &str,
        data: &str,
        location: DataLocation,
    ) -> Option<String> {
        let source = self.sources.get(source_id)?;
        let taint_id = generate_taint_id();
        let data_hash = hash_data(data);
        let sensitivity = SensitivityLevel::from(source.sensitivity.as_str());

        let tainted = TaintedData {
            id: taint_id.clone(),
            source_id: source_id.to_string(),
            data_hash: data_hash.clone(),
            sensitivity: source.sensitivity.clone(),
            location,
            propagated_from: vec![],
            tainted_at: current_timestamp(),
            can_sanitize: sensitivity <= SensitivityLevel::Confidential,
            last_accessed: current_timestamp(),
            access_count: 1.0,
        };

        *self.stats.by_sensitivity
            .entry(source.sensitivity.clone())
            .or_insert(0.0) += 1.0;
        self.stats.total_tainted += 1.0;

        self.hash_to_taint.insert(data_hash, taint_id.clone());
        self.tainted.insert(taint_id.clone(), tainted);

        Some(taint_id)
    }

    /// Propagate taint from one data to another
    pub fn propagate(
        &mut self,
        source_taint_id: &str,
        new_data: &str,
        new_location: DataLocation,
        propagation_type: PropagationType,
        operation: &str,
    ) -> Option<String> {
        let source_taint = self.tainted.get(source_taint_id)?;
        let new_taint_id = generate_taint_id();
        let data_hash = hash_data(new_data);

        // Build propagation chain
        let mut propagated_from = source_taint.propagated_from.clone();
        propagated_from.push(source_taint_id.to_string());

        let new_tainted = TaintedData {
            id: new_taint_id.clone(),
            source_id: source_taint.source_id.clone(),
            data_hash: data_hash.clone(),
            sensitivity: source_taint.sensitivity.clone(),
            location: new_location,
            propagated_from,
            tainted_at: current_timestamp(),
            can_sanitize: source_taint.can_sanitize,
            last_accessed: current_timestamp(),
            access_count: 1.0,
        };

        // Record propagation
        let propagation = TaintPropagation {
            id: generate_taint_id(),
            source_id: source_taint_id.to_string(),
            target_id: new_taint_id.clone(),
            propagation_type: format!("{:?}", propagation_type).to_lowercase(),
            operation: operation.to_string(),
            timestamp: current_timestamp(),
        };
        self.propagations.push(propagation);
        self.stats.total_propagations += 1.0;

        self.hash_to_taint.insert(data_hash, new_taint_id.clone());
        self.tainted.insert(new_taint_id.clone(), new_tainted);

        Some(new_taint_id)
    }

    /// Check if data can flow to a sink
    pub fn can_flow_to(&self, taint_id: &str, sink: &str) -> FlowDecision {
        let tainted = match self.tainted.get(taint_id) {
            Some(t) => t,
            None => return FlowDecision::allowed("No taint found"),
        };

        let sink_policy = match self.allowed_sinks.get(sink) {
            Some(p) => p,
            None => return FlowDecision::denied("Unknown sink"),
        };

        let sensitivity = SensitivityLevel::from(tainted.sensitivity.as_str());

        if sensitivity > sink_policy.max_sensitivity {
            return FlowDecision::denied(&format!(
                "Sensitivity {} exceeds sink maximum {}",
                tainted.sensitivity,
                sink_policy.max_sensitivity.name()
            ));
        }

        if sink_policy.require_sanitization && !tainted.can_sanitize {
            return FlowDecision::requires_sanitization(
                "Sink requires sanitization for this data"
            );
        }

        FlowDecision::allowed(&format!("Flow permitted to {}", sink))
    }

    /// Check if data is tainted by hash
    pub fn is_tainted(&self, data: &str) -> bool {
        let hash = hash_data(data);
        self.hash_to_taint.contains_key(&hash)
    }

    /// Get taint by data hash
    pub fn get_taint_by_data(&self, data: &str) -> Option<&TaintedData> {
        let hash = hash_data(data);
        self.hash_to_taint.get(&hash).and_then(|id| self.tainted.get(id))
    }

    /// Get taint by ID
    pub fn get_taint(&self, taint_id: &str) -> Option<&TaintedData> {
        self.tainted.get(taint_id)
    }

    /// Get all taints from a source
    pub fn taints_from_source(&self, source_id: &str) -> Vec<&TaintedData> {
        self.tainted
            .values()
            .filter(|t| t.source_id == source_id)
            .collect()
    }

    /// Get propagation chain for a taint
    pub fn get_propagation_chain(&self, taint_id: &str) -> Vec<&TaintedData> {
        let mut chain = Vec::new();
        let mut visited = HashSet::new();
        let mut current = taint_id.to_string();

        while let Some(taint) = self.tainted.get(&current) {
            if visited.contains(&current) {
                break;
            }
            visited.insert(current.clone());
            chain.push(taint);

            if let Some(parent) = taint.propagated_from.last() {
                current = parent.clone();
            } else {
                break;
            }
        }

        chain
    }

    /// Clear taint (mark as sanitized)
    pub fn clear_taint(&mut self, taint_id: &str) -> bool {
        if let Some(taint) = self.tainted.remove(taint_id) {
            self.hash_to_taint.remove(&taint.data_hash);
            self.stats.total_tainted -= 1.0;
            true
        } else {
            false
        }
    }

    /// Get statistics
    pub fn stats(&self) -> TaintStatsResult {
        TaintStatsResult {
            total_sources: self.stats.total_sources,
            total_tainted: self.stats.total_tainted,
            total_propagations: self.stats.total_propagations,
            by_source_type: self.stats.by_source_type.clone(),
            by_sensitivity: self.stats.by_sensitivity.clone(),
        }
    }

    /// Clear all taints
    pub fn clear_all(&mut self) {
        self.tainted.clear();
        self.propagations.clear();
        self.hash_to_taint.clear();
        self.stats.total_tainted = 0.0;
        self.stats.total_propagations = 0.0;
    }
}

fn generate_taint_id() -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::time::{SystemTime, UNIX_EPOCH};

    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();

    let mut hasher = DefaultHasher::new();
    now.hash(&mut hasher);

    format!("taint-{:016x}", hasher.finish())
}

fn hash_data(data: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data.as_bytes());
    hex::encode(&hasher.finalize()[..8])
}

fn current_timestamp() -> f64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs_f64()
}

/// Decision about whether data can flow
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct FlowDecision {
    pub allowed: bool,
    pub reason: String,
    pub requires_sanitization: bool,
}

impl FlowDecision {
    fn allowed(reason: &str) -> Self {
        FlowDecision {
            allowed: true,
            reason: reason.to_string(),
            requires_sanitization: false,
        }
    }

    fn denied(reason: &str) -> Self {
        FlowDecision {
            allowed: false,
            reason: reason.to_string(),
            requires_sanitization: false,
        }
    }

    fn requires_sanitization(reason: &str) -> Self {
        FlowDecision {
            allowed: true,
            reason: reason.to_string(),
            requires_sanitization: true,
        }
    }
}

/// Taint statistics result
#[derive(Debug, Clone, Serialize, Deserialize)]
#[napi(object)]
pub struct TaintStatsResult {
    pub total_sources: f64,
    pub total_tainted: f64,
    pub total_propagations: f64,
    pub by_source_type: HashMap<String, f64>,
    pub by_sensitivity: HashMap<String, f64>,
}

/// Create a taint tracker
#[napi_derive::napi]
pub fn create_taint_tracker() -> TaintTrackerHandle {
    TaintTrackerHandle {
        tracker: TaintTracker::new(),
    }
}

/// Handle for taint tracker
#[napi]
pub struct TaintTrackerHandle {
    tracker: TaintTracker,
}

#[napi]
impl TaintTrackerHandle {
    /// Register a source
    #[napi]
    pub fn register_source(
        &mut self,
        source_type: String,
        sensitivity: String,
        tags: Vec<String>,
    ) -> String {
        let st = match source_type.to_lowercase().as_str() {
            "user_input" | "user" => TaintSourceType::UserInput,
            "file" | "filesystem" => TaintSourceType::FileSystem,
            "network" | "api" => TaintSourceType::Network,
            "env" | "environment" => TaintSourceType::Environment,
            "secrets" | "vault" => TaintSourceType::Secrets,
            "database" | "db" => TaintSourceType::Database,
            "agent" => TaintSourceType::AgentGenerated,
            "tool" => TaintSourceType::ToolOutput,
            "memory" => TaintSourceType::Memory,
            _ => TaintSourceType::External,
        };

        let sens = SensitivityLevel::from(sensitivity.as_str());
        self.tracker.register_source(st, sens, tags)
    }

    /// Taint data
    #[napi]
    pub fn taint(
        &mut self,
        source_id: String,
        data: String,
        location_type: String,
        identifier: String,
    ) -> Option<String> {
        let location = DataLocation {
            location_type,
            identifier,
            context: None,
        };
        self.tracker.taint_data(&source_id, &data, location)
    }

    /// Propagate taint
    #[napi]
    pub fn propagate(
        &mut self,
        source_taint_id: String,
        new_data: String,
        location_type: String,
        identifier: String,
        propagation_type: String,
        operation: String,
    ) -> Option<String> {
        let location = DataLocation {
            location_type,
            identifier,
            context: None,
        };

        let prop_type = match propagation_type.to_lowercase().as_str() {
            "assignment" => PropagationType::Assignment,
            "parameter" => PropagationType::Parameter,
            "return" => PropagationType::Return,
            "concatenation" => PropagationType::Concatenation,
            "collection" => PropagationType::CollectionInclusion,
            "property" => PropagationType::Property,
            "transformation" => PropagationType::Transformation,
            _ => PropagationType::Aggregation,
        };

        self.tracker.propagate(&source_taint_id, &new_data, location, prop_type, &operation)
    }

    /// Check if can flow to sink
    #[napi]
    pub fn can_flow(&self, taint_id: String, sink: String) -> FlowDecision {
        self.tracker.can_flow_to(&taint_id, &sink)
    }

    /// Check if data is tainted
    #[napi]
    pub fn is_tainted(&self, data: String) -> bool {
        self.tracker.is_tainted(&data)
    }

    /// Get taint info
    #[napi]
    pub fn get_taint(&self, taint_id: String) -> Option<TaintedData> {
        self.tracker.get_taint(&taint_id).cloned()
    }

    /// Get statistics
    #[napi]
    pub fn stats(&self) -> TaintStatsResult {
        self.tracker.stats()
    }

    /// Clear a taint
    #[napi]
    pub fn clear(&mut self, taint_id: String) -> bool {
        self.tracker.clear_taint(&taint_id)
    }

    /// Clear all taints
    #[napi]
    pub fn clear_all(&mut self) {
        self.tracker.clear_all();
    }
}
