/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GrepMatch {
  path: string
  line: number
  column: number
  content: string
  contextBefore: Array<string>
  contextAfter: Array<string>
}

export interface GrepOptions {
  caseSensitive?: boolean
  caseInsensitive?: boolean
  contextLines?: number
  maxResults?: number
  includePatterns: Array<string>
  excludePatterns: Array<string>
}

export interface GrepResult {
  matches: Array<GrepMatch>
  totalCount: number
}

export interface HashResult {
  hash: string
  algorithm: string
}

export interface HighlightResult {
  html: string
  theme: string
}

export interface HighlightDiffResult {
  /** ANSI-colored diff output */
  output: string
  /** Number of added lines */
  additions: number
  /** Number of deleted lines */
  deletions: number
  /** Number of hunks */
  hunks: number
}

export interface DiffOptions {
  /** File path to display in header */
  filePath?: string
  /** Number of context lines around changes */
  contextLines?: number
}

export interface StructureItem {
  kind: string
  name: string
  line: number
  column: number
  endLine?: number
  endColumn?: number
  children: Array<StructureItem>
}

export interface StructureOptions {
  includeComments?: boolean
  maxDepth?: number
}

export interface StructureResult {
  items: Array<StructureItem>
  language: string
}

export interface ToolPair {
  tool1: string
  tool2: string
  target1: string
  target2: string
  similarity: number
}

export interface ToolPairsResult {
  pairs: Array<ToolPair>
  totalCalls: number
}

export interface DiffHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  content: string
}

export interface PatternResult {
  tools: Array<string>
  support: number
  confidence: number
}

export interface ToolCountEntry {
  toolName: string
  count: number
}

export interface ContextStatsResult {
  totalTokens: number
  userTokens: number
  assistantTokens: number
  toolResultTokens: number
  messageCount: number
}

export interface MultiEditEntry {
  filePath: string
  oldText: string
  newText: string
}

export interface MultiEditPreviewEntry {
  filePath: string
  diff: string
  additions: number
  deletions: number
}

export interface MultiEditResult {
  success: boolean
  errors: Array<string>
  modifiedFiles: Array<string>
}

export function analyzePatterns(messages: Array<string>, minSupport?: number): Array<PatternResult>
export function countToolUsesNative(messages: Array<string>): Array<ToolCountEntry>
export function calculateContextStats(messages: Array<string>): ContextStatsResult
export function grepSearch(pattern: string, path: string, options?: GrepOptions): Promise<GrepResult>
export function calculateHash(content: string, algorithm?: string): HashResult
export function countTokens(text: string): number
export function highlightCode(code: string, language: string): HighlightResult
export function highlightMarkdown(markdown: string): HighlightResult
export function analyzeStructure(filePath: string, content: string): StructureResult
export function findToolPairs(logs: Array<string>, threshold?: number): ToolPairsResult
export function highlightDiff(oldText: string, newText: string, options?: DiffOptions): HighlightDiffResult
export function calculateDiff(oldText: string, newText: string): Array<DiffHunk>
export function validateMultiEdits(edits: Array<MultiEditEntry>): Array<string>
export function previewMultiEdits(edits: Array<MultiEditEntry>): Array<MultiEditPreviewEntry>
export function applyMultiEdits(edits: Array<MultiEditEntry>): MultiEditResult
